name: Publish package to GitHub Packages
on:
  workflow_dispatch:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  notify:
    runs-on: ubuntu-latest 
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build package 
        run: |
          mvn -B -DskipTests clean package
          
      - name: Run tests
        run: |
          mvn test
          ls -la
          pwd
          ls -la target/surefire-reports/
