name: publish reports to slack
on:
  workflow_dispatch:
  push:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  notify:
    runs-on: ubuntu-latest 
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build package 
        run: |
          mvn -B -DskipTests clean package
          
      - name: Run tests
        run: |
          mvn test
          ls -la
          pwd
          ls -la target/surefire-reports/
          cat target/surefire-reports/com.mycompany.app.AppTest.txt
          echo "REPORT=$(cat target/surefire-reports/com.mycompany.app.AppTest.txt)" >> $GITHUB_ENV
          
      - name: Zip reports
        run: zip -r reports.zip target/surefire-reports

      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.25.0
      #   with:
      #     # file-path: "./target/surefire-reports/TEST-com.mycompany.app.AppTest.xml"
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      #     channel-id: 'C06LP66NS1F'
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{env.REPORT}} }",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result:  ${{env.REPORT}} }}"
      #             }
      #           }
      #         ]
      #       }  
      #     # For posting a simple plain text message
      #     slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: List XML Files
        id: list-xml-files
        run: |
          XML_FILES=$(find target/surefire-reports -type f -name "*.xml")
          echo "::set-output name=xml_files::$XML_FILES"

      - name: Send XML Files to Slack
        env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  # Add your Slack webhook URL to GitHub Secrets
        run: |
          for file in ${{ steps.list-xml-files.outputs.xml_files }}; do
            curl -F file=@$file -F "initial_comment=Shakes the cat" -F channels=C06LP66NS1F -H "Authorization: Bearer $SLACK_BOT_TOKEN" https://slack.com/api/files.upload
          done
